---
title: "Project Proposal"
author: "Tofu-FC - Huiwen Wang, Rocky Zhang, Darrick Zhang"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
library(tidyverse)
library(tidymodels)
# add other packages as needed

# add code to load data
```

## Introduction

### Subject Matter

Mushrooms are vital to the general wellness of the ecosystem, decomposing and recycling the nutrients in the soil. Mushrooms also provides a valuable food source full of nutrients for human beings and other important organisms. With this in mind, we are interested to see if there are any environmental factors and physical features of mushrooms that can help curious human avoid poisonous mushrooms that may grow in their yard. Ultimately the study of mushrooms is essential for safety and well-being.

"The ingestion of wild and potentially toxic mushrooms is common in the United States, with poison centers logging cases in the National Poison Data System (NPDS) for over 30 years. From 1999 to 2016, there were 133,700 reported cases of mushroom exposure, mostly unintentional and involving children under six years old. While the majority of cases resulted in no or minor harm, there were 704 instances of major harm and 52 fatalities, primarily due to cyclopeptide-producing mushrooms ingested unintentionally by older adults. Misidentification of edible mushroom species is a common cause of poisoning and may be preventable through education"(Brandenburg, William E, and Karlee J Ward. “Mushroom poisoning epidemiology in the United States.” Mycologia vol. 110,4 (2018): 637-641. doi:10.1080/00275514.2018.1479561). Because of this research and that of the nature, accurate classification of mushrooms is crucial for preventing poisoning incidents. Many toxic mushrooms closely resemble edible varieties, making it easy for foragers to misidentify them. So our research will focus on **what physical features and environmental factors of mushrooms human can use to identify toxic/poisonous mushrooms in the wild**. By conducting a research on how to distinguish between safe and dangerous species, we can mitigate the incidence of mushroom poisoning and ensure safer foraging practices.

### Hypotheses:

1.  Mushrooms in the wild with obvious physical features like white gills, white rings, red caps, or red stems tend to be poisonous. We want to explore this hypothesis because mushrooms with obvious physical traits are more likely to be spotted by animals, which would provide an evolutionary disadvantage unless they contain certain self-defense mechanisms, such as poison or toxins.

2.  The habitat of the mushrooms would likely affect whether they're poisonous. We form this hypothesis because in specific habitats, mushrooms might face intense competition for resources such as nutrients, light, or space. Producing toxins can give them a competitive edge by inhibiting the growth of other fungi or microorganisms. In addition, different environmental conditions such as temperature, humidity, and light in various location can affect the production of secondary metabolites, including toxins.

## Data description

The dataset we used can be found here: [Mushroom Dataset](https://www.kaggle.com/datasets/uciml/mushroom-classification/data)

The data was curated on April 26, 1987, and submitted to the UCI by the National Audubon Society Field Guide. The National Audubon Society conducted extensive field research throughout North America, recording their observations on various aspects of mushrooms. Their research incoperate a wide range of physical characteristics, including size, shape, color, and texture of the mushrooms. Additionally, they documented environmental factors such as the type of habitat and seasonal variations. Importantly, the study also focused on the toxicity of the mushrooms, noting which species were poisonous. This comprehensive dataset provides valuable insights into the relationship between mushrooms and their environments, contributing significantly to the understanding of the factors influencing mushroom toxicity.

The dataset includes characteristics like cap diameter (quantitative), cap shape (qualitative), stem height and width (quantitative), type of stem root and color (qualitative), ring type (qualitative), habitat (qualitative), and whether the mushroom is edible or poisonous (qualitative). The dataset contains a varieties of mushrooms from different families and speices with any speices or family dominating the dataset.

## Exploratory data analysis

...

## Analysis approach

For the first hypothesis, we select variables representing apparent physical features like "cap-color", "gill-color", "ring-type", "veil-color", and "stalk-color-below-ring" 
as the explanatory variables.

For the second hypothesis, we'll focus on the environmental factors, using variables "habitat" as the explanatory variables.

For both hypotheses, we'll use logistic regression because our response variable is a binary categorical variable ("classes" can only be "e" representing "edible" or "p" representing "poisonous").

## Data dictionary

The data dictionary can be found [here](https://github.com/sta221-fa24/project-Tofu-FC/blob/main/data/README.md)
