---
title: "Your project title"
author: "Team Name: Team member 1, Team member 2, Team member 3, Team member 4"
date: "Update date"
format: pdf
execute: 
  warning: false
  message: false
  echo: false
editor: visual
---

```{r}
#| label: load packages and data

library(tidyverse)
library(tidymodels)
library(dbplyr)
library(knitr)
library(gridExtra)
# add other packages as needed

mushrooms <- read.csv2("data/mushrooms_dataset.csv")
```

```{r}
#| label: univariate predictor distribution

predictors <- c("cap.diameter", "cap.shape", "stem.root",
                "stem.color", "ring.type", "habitat", "season")
response_var <- "class"

# Make Quantitative data numerical
mushrooms$cap.diameter <- as.numeric(mushrooms$cap.diameter)
mushrooms$stem.height <- as.numeric(mushrooms$stem.height)
mushrooms$stem.width <- as.numeric(mushrooms$stem.width)

p1 <- ggplot(mushrooms, aes(x = cap.diameter)) +
    geom_histogram() +
    labs(title = "Cap diameter")
p2 <- ggplot(mushrooms, aes(x = cap.shape)) +
    geom_bar() +
    labs(title = "Cap shape")
p3 <- ggplot(mushrooms, aes(x = stem.root)) +
    geom_bar() +
    labs(title = "Stem root")
p4 <- ggplot(mushrooms, aes(x = stem.color)) +
    geom_bar() +
    labs(title = "Stem color")
p5 <- ggplot(mushrooms, aes(x = ring.type)) +
    geom_bar() +
    labs(title = "Ring type")
p6 <- ggplot(mushrooms, aes(x = habitat)) +
    geom_bar() +
    labs(title = "Habitat")
p7 <- ggplot(mushrooms, aes(x = season)) +
    geom_bar() +
    labs(title = "Season")
grid.arrange(p1,p2,p3,p4,p5,p6,p7, heights = 4)
```

```{r}
#| label: bivariate EDA
# g1 <- ggplot(mushrooms, aes_string(x = "cap.diameter", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs cap diameter")
# g2 <- ggplot(mushrooms, aes_string(x = "cap.shape", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs cap shape")
# g3 <- ggplot(mushrooms, aes_string(x = "stem.root", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs stem root")
# g4 <- ggplot(mushrooms, aes_string(x = "stem.color", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs stem color")
# g5 <- ggplot(mushrooms, aes_string(x = "ring.type", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs ring type")
# g6 <- ggplot(mushrooms, aes_string(x = "habitat", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs habitat")
# g7 <- ggplot(mushrooms, aes_string(x = "season", y = response_var)) +
#     geom_point() +
#     labs(title = "Response vs season")

# grid.arrange(g1,g2,g3,g4,g5,g6,g7)
```

Your written report goes here!

::: callout-important
Before you submit, make sure your code chunks are turned off with `echo: false` and there are no warnings or messages with `warning: false` and `message: false` in the YAML.
:::
